'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WWWords.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property av1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("av1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property av2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("av2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property av3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("av3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property background1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property background2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property background3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to anal
        '''anus
        '''arse
        '''ass
        '''ballsack
        '''bastard
        '''bitch
        '''biatch
        '''bloody
        '''blowjob
        '''blow job
        '''bollock
        '''bollok
        '''boner
        '''boob
        '''bugger
        '''bum
        '''butt
        '''buttplug
        '''clitoris
        '''cock
        '''coon
        '''crap
        '''cunt
        '''damn
        '''dick
        '''dildo
        '''dyke
        '''fag
        '''feck
        '''fellate
        '''fellatio
        '''felching
        '''fuck
        '''f u c k
        '''fudgepacker
        '''fudge packer
        '''flange
        '''Goddamn
        '''God damn
        '''hell
        '''homo
        '''jerk
        '''jizz
        '''knobend
        '''knob end
        '''labia
        '''lmao
        '''lmfao
        '''muff
        '''nigger
        '''nigga
        '''omg
        '''penis
        '''piss
        '''poop
        '''prick
        '''pube
        '''pussy
        '''queer
        '''scrotum
        '''sex
        '''shit
        '''s hit
        '''sh1t
        '''slut
        '''smegma
        '''spunk
        '''tit
        '''tosser        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property BadWords() As String
            Get
                Return ResourceManager.GetString("BadWords", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property ball() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ballx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ballx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blacklocation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blacklocation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bomb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bomb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bul() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bul", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bulbasor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bulbasor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bulbasor2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bulbasor2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chanmander() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chanmander", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chanmanderx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chanmanderx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chat1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chat1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chinacheck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chinacheck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chinaflag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chinaflag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property core() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("core", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property electric() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("electric", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property electricpng() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("electricpng", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property electrics() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("electrics", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property female() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("female", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property firepng() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("firepng", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fires() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fires", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property flag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property grass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property grasses() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grasses", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property grasspng() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grasspng", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property greece() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("greece", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property greececheck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("greececheck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property idea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("idea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property instinct() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("instinct", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property italy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("italy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property italycheck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("italycheck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kitchanismo() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("kitchanismo", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property male() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("male", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minigame() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minigame", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mystic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mystic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property noflag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noflag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pikachu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pikachu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pokeball() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pokeball", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property psyduck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("psyduck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rattata() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rattata", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rattatax() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rattatax", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rocket() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rocket", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property squirtle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("squirtle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property squirtlex() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("squirtlex", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sti_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sti-logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property time() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("time", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property valor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("valor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to aa
        '''aah
        '''aahed
        '''aahing
        '''aahs
        '''aal
        '''aalii
        '''aaliis
        '''aals
        '''aardvark
        '''aardvarks
        '''aardwolf
        '''aardwolves
        '''aargh
        '''aas
        '''aasvogel
        '''aasvogels
        '''aba
        '''abaca
        '''abacas
        '''abaci
        '''aback
        '''abacus
        '''abacuses
        '''abaft
        '''abaka
        '''abakas
        '''abalone
        '''abalones
        '''abamp
        '''abampere
        '''abamperes
        '''abamps
        '''abandon
        '''abandoned
        '''abandoning
        '''abandonment
        '''abandonments
        '''abandons
        '''abas
        '''abase
        '''abased
        '''abasedly
        '''abasement
        '''abasements
        '''abaser
        '''abasers
        '''abases
        '''abash
        '''abashed
        '''abashes
        '''abashing
        '''abashment
        '''abashments
        '''abasing
        '''abatable
        '''abate
        '''abated
        '''abatement
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property WordList() As String
            Get
                Return ResourceManager.GetString("WordList", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
